export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const COUNT_CART_TOTALS = "COUNT_CART_TOTALS";
export const ADD_TO_CART = "ADD_TO_CART";
export const CHANGE_CART_ITEM_AMOUNT = "CHANGE_CART_ITEM_AMOUNT";
